<svelte:head>
  <title>Privacy Policy</title>
  <meta
    name="description"
    content="Information about data processed on the website"
  />
  <html lang="en" />
</svelte:head>

<div class="privacy">
  <div class="privacy__content">
    <h1 class="heading-l">Privacy Policy</h1>
    <p class="text-m">Last updated: April 20, 2021</p>
    <p class="text-m">
      This Privacy Policy describes Our policies and procedures on the
      collection, use and disclosure of Your information when You use the
      Service and tells You about Your privacy rights and how the law protects
      You.
    </p>
    <p class="text-m">
      We use Your Personal data to provide and improve the Service. By using the
      Service, You agree to the collection and use of information in accordance
      with this Privacy Policy. This Privacy Policy has been created with the
      help of the <a
        href="https://www.privacypolicies.com/privacy-policy-generator/"
        target="_blank">Privacy Policy Generator</a
      >.
    </p>
    <h2 class="heading-m">Interpretation and Definitions</h2>
    <h3 class="heading-s">Interpretation</h3>
    <p class="text-m">
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions. The following definitions shall have the
      same meaning regardless of whether they appear in singular or in plural.
    </p>
    <h3 class="heading-s">Definitions</h3>
    <p class="text-m">For the purposes of this Privacy Policy:</p>
    <ul>
      <li class="text-m">
        <p class="text-m">
          <strong>Account</strong> means a unique account created for You to access
          our Service or parts of our Service.
        </p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>Company</strong> (referred to as either &quot;the Company&quot;,
          &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers
          to Michael Rieger.
        </p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>Cookies</strong> are small files that are placed on Your computer,
          mobile device or any other device by a website, containing the details
          of Your browsing history on that website among its many uses.
        </p>
      </li>
      <li class="text-m">
        <p class="text-m"><strong>Country</strong> refers to: Austria</p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>Device</strong> means any device that can access the Service such
          as a computer, a cellphone or a digital tablet.
        </p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>Personal Data</strong> is any information that relates to an identified
          or identifiable individual.
        </p>
      </li>
      <li class="text-m">
        <p class="text-m"><strong>Service</strong> refers to the Website.</p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>Service Provider</strong> means any natural or legal person who
          processes the data on behalf of the Company. It refers to third-party companies
          or individuals employed by the Company to facilitate the Service, to provide
          the Service on behalf of the Company, to perform services related to the
          Service or to assist the Company in analyzing how the Service is used.
        </p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>Third-party Social Media Service</strong> refers to any website
          or any social network website through which a User can log in or create
          an account to use the Service.
        </p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>Usage Data</strong> refers to data collected automatically, either
          generated by the use of the Service or from the Service infrastructure
          itself (for example, the duration of a page visit).
        </p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>Website</strong> refers to Michael Rieger, accessible from
          <a
            href="https://michaelrieger.dev"
            rel="external nofollow noopener"
            target="_blank">https://michaelrieger.dev</a
          >
        </p>
      </li>
      <li class="text-m">
        <p class="text-m">
          <strong>You</strong> means the individual accessing or using the Service,
          or the company, or other legal entity on behalf of which such individual
          is accessing or using the Service, as applicable.
        </p>
      </li>
    </ul>


    <h2 class="heading-m">Collecting and Using Your Personal Data</h2>
    <h3 class="heading-s">Types of Data Collected</h3>
    <h4 class="text-l">Personal Data</h4>
    <p class="text-m">
      We do not collet any personal data.
    </p>
    <h4 class="text-l">Tracking Technologies and Cookies</h4>
    <p class="text-m">We do not use any cookies.</p>
    <ul>
      <li class="text-m">
        <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed
        on Your Device. You can instruct Your browser to refuse all Cookies or to
        indicate when a Cookie is being sent. However, if You do not accept Cookies,
        You may not be able to use some parts of our Service. Unless you have adjusted
        Your browser setting so that it will refuse Cookies, our Service may use
        Cookies.
      </li>
    </ul>
    

    <h2 class="heading-m">Links to Other Websites</h2>
    <p class="text-m">
      Our Service may contain links to other websites that are not operated by
      Us. If You click on a third party link, You will be directed to that third
      party's site. We strongly advise You to review the Privacy Policy of every
      site You visit.
    </p>
    <p class="text-m">
      We have no control over and assume no responsibility for the content,
      privacy policies or practices of any third party sites or services.
    </p>

    
    <h2 class="heading-m">Changes to this Privacy Policy</h2>
    <p class="text-m">
      We may update Our Privacy Policy from time to time. We will notify You of
      any changes by posting the new Privacy Policy on this page.
    </p>
    <p class="text-m">
      We will let You know via email and/or a prominent notice on Our Service,
      prior to the change becoming effective and update the &quot;Last
      updated&quot; date at the top of this Privacy Policy.
    </p>
    <p class="text-m">
      You are advised to review this Privacy Policy periodically for any
      changes. Changes to this Privacy Policy are effective when they are posted
      on this page.
    </p>
    <h2 class="heading-m">Contact Us</h2>
    <p class="text-m">
      If you have any questions about this Privacy Policy, You can contact us:
    </p>
    <ul>
      <li class="text-m">By email: hello@michaelrieger.dev</li>
    </ul>
  </div>
</div>

<style>
  .privacy {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 4em var(--content-side-padding);
  }

  .privacy__content {
    width: 100%;
    max-width: 1440px;
  }

  .privacy__content > * + * {
    margin-top: 1em;
  }

  li + li {
    margin-top: 0.5em;
  }
</style>
